/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    GallaryView: typeof import('./src/components/GallaryView.vue')['default']
    MainFooter: typeof import('./src/components/common/MainFooter.vue')['default']
    MainGallary: typeof import('./src/components/MainGallary.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
  }
}
