/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    Drawer: typeof import('./src/components/Drawer.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckTag: typeof import('element-plus/es')['ElCheckTag']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElPageHeader: typeof import('element-plus/es')['ElPageHeader']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FilterMenu: typeof import('./src/components/common/FilterMenu.vue')['default']
    GallaryToolBar: typeof import('./src/components/GallaryToolBar.vue')['default']
    GallaryView: typeof import('./src/components/GallaryView.vue')['default']
    MainContent: typeof import('./src/components/pages/MainContent.vue')['default']
    MainFooter: typeof import('./src/components/common/MainFooter.vue')['default']
    MainGallary: typeof import('./src/components/MainGallary.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    Select: typeof import('./src/components/Select.vue')['default']
    ToolBar: typeof import('./src/components/ToolBar.vue')['default']
  }
}
